// <auto-generated>
namespace Another;

[PrimS.BoolParameterGenerator.GenerateBinaryEnum("Yes", "No")]
public partial class IsValidBinaryEnumTwo
{ }

[PrimS.BoolParameterGenerator.GenerateBinaryEnum("Yes", "No")]
public partial class IsValidBinaryEnumThree
{ }

[PrimS.BoolParameterGenerator.GenerateBoolEnum("Yes", "No")]
public partial class IsValidBoolTwo
{ }

[PrimS.BoolParameterGenerator.GenerateBoolEnum("Yes", "No")]
public partial class IsValidBoolThree
{ }
